---
- name: Deploy Docker Images
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check using whoami
      shell: whoami

    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file from host machine
      copy:
        src: ./docker-compose.yml
        dest: /home/yasha/Desktop/AfterAnsibleDeployment/docker-compose.yml

