---
- name: Deploy docker images
  hosts: all
  
  gather_facts: yes
  become: yes
  tasks:        
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build

    - name: Prune the dangling Docker images
      command: /opt/homebrew/bin/docker image prune --force
