version: "2"
services:
  server:
    image: anshul1601/backend_image
    container_name: backend
    restart: always
    ports:
      - "5005:5005"
    links:
      - mongo
      
  client:
    image: anshul1601/frontend_image
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"


  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
